//! meridian-core — the MERIDIAN cache engine (HELIOS v5 spec, Phases 0–26).

pub mod aof;
pub mod cdc;
pub mod chronos;
pub mod cluster;
pub mod compact;
pub mod compute;
pub mod crdt;
pub mod deadline;
pub mod delta;
pub mod engine;
pub mod epoch;
pub mod flash;
pub mod hash;
pub mod json_tape;
pub mod l0;
pub mod mesh;
pub mod net;
pub mod oracle;
pub mod prices;
pub mod probabilistic;
pub mod security;
pub mod shard_count;
pub mod side_planes;
pub mod spectrum;
pub mod stream;
pub mod types;
pub mod vector;
pub mod vector_plane;
pub mod zset;

pub use engine::{Engine, EngineOptions, EngineStats, SetOpts, SetOutcome, Slo, TtlStatus, ValueRef, PROBE_LIMIT};
pub use oracle::{Dep, OracleIndex};
pub use cdc::{CdcOp, CdcRecord, DegradationLevel, WatermarkTracker, OriginTokenBucket};
pub use delta::{DeltaOp, apply_delta, DifferentialAuditor};
pub use chronos::{ChronosStore, VersionRecord};
pub use prices::{DualAscentEngine, PriceVector};
pub use spectrum::{Approx, FidelityLevel};
pub use deadline::{DeadlineScheduler, DegradeAction};
pub use flash::FlashTier;
pub use mesh::{MeshCluster, MeshNode, GossipMessage};
pub use probabilistic::{HyperLogLog, CountMinSketch, CuckooFilter, HLL_REGISTERS};
pub use crdt::{PnCounter, LwwSet};
pub use json_tape::JsonValue;
pub use zset::{ZSet, ZSetItem};
pub use vector_plane::{VectorIndex, QuantizedVector};
pub use compute::opcodes::*;
pub use compute::{MeridianVM, VmResult, VmError, StoredFunction, FunctionCatalog, Compiler, DEFAULT_GAS_BUDGET};
pub use stream::{Stream, StreamEntry, StreamId, ConsumerGroup, PendingEntry, PubSubBus};
pub use aof::{AofOpcode, AofRecord, AofWriter, AofSyncPolicy, AofRecovery, AofRecoveryResult, AOF_MAGIC};
pub use security::{User, SecurityManager, AuthError, AuditBlock, AuditLedger, PERM_READ, PERM_WRITE, PERM_ADMIN, PERM_STREAM, PERM_COMPUTE, PERM_AUDIT, PERM_ALL};
pub use net::{UringEngine, Sqe, Cqe, UringOpcode};
pub use vector::{HnswIndex, HnswNode, cosine_similarity, euclidean_distance_sq, dot_product};
pub use cluster::{SlotTable, SlotState, MigrationController, MigrationTask, MigrationPhase, WanMesh, WanDelta, VectorClock, get_slot, crc16, TOTAL_SLOTS};
pub use compact::{CompactBytes, TaggedPtr, compress_value, decompress_value, INLINE_CAPACITY, COMPRESSION_THRESHOLD};
pub use types::WAYS;
